import type { Metadata } from 'next'
import './globals.css'
import { UserProvider } from '@auth0/nextjs-auth0/client'
import { Toaster } from 'react-hot-toast'

import { Average_Sans } from 'next/font/google'

const roboto = Average_Sans({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Dashboard',
  description: 'Generated by create next app',

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={roboto.className}>
      <UserProvider>
        <body className='w-screen h-screen '>
          {children}
          <Toaster />
        </body>
      </UserProvider>
    </html>
  )
}
